sudo: required

language: generic

services:
  - docker

env:
  global:
    - DOCKER_IMAGE=gographics/imagick.v2:im-$IMAGEMAGICK6_VERSION
    - CACHE_DIR=$HOME/.cache
    - GOCACHE=$CACHE_DIR/go-build
    - GOPATH=$CACHE_DIR/go

cache:
  directories:
    - $GOCACHE
    - $GOPATH/pkg

before_script:
  - docker pull "$DOCKER_IMAGE"

script:
  - >
    docker run -it --rm \
      -v $PWD:/go/projects/imagick \
      -v ${GOCACHE}:/root/.cache/go-build \
      -v ${GOPATH}/pkg:/go/pkg \
      "$DOCKER_IMAGE"
