name: ci
on: [push, pull_request]

jobs:
  test_go:
    name: Test go-${{ matrix.go }} on ${{ matrix.os }}
    strategy:
      matrix:
        go: [1.14.x]
        os: [windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Setup go
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go }}

      - name: Setup MSYS2
        uses: numworks/setup-msys2@v1
        with:
          update: true

      - name: Install deps
        run: |
          msys2do makepkg-mingw -sCLfc --noconfirm --noprogressbar
          msys2do pacman -Sy --needed mingw-w64-x86_64-toolchain
          msys2do pacman -Sy mingw-w64-x86_64-pkg-config mingw-w64-x86_64-imagemagick mingw-w64-x86_64-gcc
          echo "Done installing deps"
          dir C:/msys2
          dir C:/msys2/mingw64/
          dir C:/msys2/mingw64/lib
          set PKG_CONFIG_PATH=/mingw64/usr/lib/pkgconfig

      - name: Test
        run: go test -v ./...

