name: ci
on: [push, pull_request]

jobs:
  test_go:
    name: Test go-${{ matrix.go }} on ${{ matrix.os }}
    strategy:
      matrix:
        go: [1.14.2]
        os: [windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Setup MSYS2
        uses: numworks/setup-msys2@v1
        with:
          update: true

      - name: Install deps
        run: |
          msys2do pacman -S --noconfirm --needed base-devel mingw-w64-x86_64-toolchain
          msys2do pacman -S --noconfirm mingw-w64-x86_64-pkg-config mingw-w64-x86_64-imagemagick
          echo 'export PATH=/c/Go1.14.2/bin:$PATH' >> ~/.bashrc
          msys2do go env
          msys2do pkg-config --cflags --libs MagickWand

      - name: Setup go
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go }}

      - name: Test
        run: msysdo go test -v ./...

