name: ci
on: [push, pull_request]

jobs:
  test_go:
    name: Test go-${{ matrix.go }} on ${{ matrix.os }}
    strategy:
      matrix:
        go: [1.14.x]
        os: [windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Setup go
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go }}

      - name: Setup MSYS2
        uses: numworks/setup-msys2@v1
        with:
          update: true
#          msystem: MSYS

      - name: Install deps
        run: |
          msys2do makepkg-mingw -sCLfc --noconfirm --noprogressbar
          msys2do pacman -Sy --needed mingw-w64-x86_64-toolchain
          #msys2do pacman -Uy mingw-w64-*-any.pkg.tar.xz
          #msys2do pacman -Sy mingw-w64-x86_64-pkg-config
          msys2do pacman -Sy mingw-w64-x86_64-imagemagick
          #msys2do pacman -Sy mingw-w64-x86_64-gcc
          echo "Done installing deps"
          msys2do pacman -Q imagemagick
          msys2do pacman -Ql imagemagick
          msys2do pacman -Qk imagemagick
          dir D:/a/_temp/msys/msys64/usr/lib/pkgconfig
          dir C:/msys64
          set PKG_CONFIG_PATH=/mingw64/usr/lib/pkgconfig
          pkg-config --cflags --libs MagickWand

      - name: Test
        run: go test -v ./...

