name: ci
on: [push, pull_request]

jobs:
  test_go:
    name: Test go-${{ matrix.go }} on ${{ matrix.os }}
    strategy:
      matrix:
        go: [1.14.x]
        os: [windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Setup MSYS2
        uses: numworks/setup-msys2@v1
        with:
          update: true

      - name: Install deps
        run: |
          msys2do makepkg-mingw -sCLfc --noconfirm --noprogressbar
          msys2do pacman -S --noconfirm --needed base-devel mingw-w64-x86_64-toolchain
          msys2do pacman -S --noconfirm mingw-w64-x86_64-pkg-config mingw-w64-x86_64-imagemagick
          set PKG_CONFIG_PATH=D:/a/_temp/msys64/mingw64/lib/pkgconfig
          dir "D:\a\_temp\msys64\mingw64\lib\pkgconfig"
          which go
          msys2do env
          msys2do pkg-config --cflags --libs MagickWand
          pkg-config --cflags --libs MagickWand

      - name: Setup go
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go }}

      - name: Test
        run: go test -v ./...

